05 hash table
ebosetalee/ds-and-algos pull request #13
Opened 2020-09-30 01:09 UTC by ebosetalee

Resolves #12 
Closes #12 

Kindly check the tests and function's arrangement in hash_table
Any corrections? @jirevwe

2020-09-30 07:50 UTC, jirevwe requested changes
You test class should have more test cases

2020-10-02 12:22 UTC, ebosetalee commented
> You test class should have more test cases

added more tests. Are they all necessary?

2020-10-02 12:40 UTC, jirevwe requested changes
The data structure is not a `list` or a `dict`. Change all the occurrences.

2020-10-02 12:40 UTC, jirevwe commented on hash_table/test/hash_table_test.py
> +    def test_delete_not_in_list(self):
```suggestion
    def test_delete_not_in_hash_table(self):
```

2020-10-02 12:40 UTC, jirevwe commented on hash_table/test/hash_table_test.py
> +    def test_delete_in_list(self):
```suggestion
    def test_delete_in_hash_table(self):
```

2020-10-02 12:40 UTC, jirevwe commented on hash_table/test/hash_table_test.py
> +    def test_get_not_in_dict(self):
```suggestion
    def test_get_not_in_hash_table(self):
```

2020-10-02 12:42 UTC, jirevwe requested changes

2020-10-02 12:42 UTC, jirevwe commented on hash_table/test/hash_table_test.py
> +    def test_set_collision(self):
```suggestion
    def test_set_collision_occurred(self):
```

2020-10-06 16:56 UTC, jirevwe reviewed
Love eet

2020-10-06 19:26 UTC, ebosetalee commented
@Jirevwe 
done

2020-10-06 20:32 UTC, yudori approved these changes
Welldone!

2020-10-06 21:20 UTC, jirevwe approved these changes

2020-10-06 21:20 UTC, merged